namespace LVC
{
    runtimeclass Contact : Microsoft.UI.Xaml.Data.INotifyPropertyChanged
    {
        Contact(String firstName, String lastName);

        String FirstName;
        String LastName;
    }
}