import "Contact.idl";

namespace LVC
{
	[default_interface]
	runtimeclass MainWindow : Microsoft.UI.Xaml.Window
	{
		MainWindow();

		Windows.Foundation.Collections.IObservableVector<Contact> Contacts{ get; };
	}
}
