import "ContactViewModel.idl";

namespace LVC
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        ContactViewModel MainViewModel;
    }
}
